"use strict";
let createProdSpan = document.querySelector('#createProduct');
let seeStockSpan = document.querySelector('#seeStock');
let cpPage = document.querySelector('#cpPage');
let stockPage = document.querySelector('#stockPage');
let nameInput = document.querySelector('#pNameInput');
let priceInput = document.querySelector('#priceInput');
let weightInput = document.querySelector('#weightInput');
let kosherInput = document.querySelector('#kosherInput');
let manInput = document.querySelector('#manInput');
let expDateInput = document.querySelector('#dateInput');
let submitBtn = document.querySelector('#submitBtn');
